version: '3'
services:
  licensingdb:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: licensingdb
