spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8071
  datasource:
    url: jdbc:postgresql://localhost:5433/licensingdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

logging:
  level:
    web: debug

server:
  port: 8090